-- DDL - DATA DEFINITION LANGUAGEM

-- CREATE <OBJETO> <NOME>;
-- PARA CRIAR UM REPOSITÓRIO: SCHEMA OU DATABASE
-- CREATE DATABASE AULA;

-- USE <NOME DO SCHEMA>
-- USE AULA; 

-- CREATE TABLE FUNCIONARIO(
-- IDF INT auto_increment, 
--  VARCHAR(50) NOT NULL, 
-- DATANASCIMENTO DATE NOT NULL,
-- PRIMARY KEY (IDF));

-- SELECT <NOME_COLUNAS, * PARA TODOS>
-- FROM TABELA
-- WHERE <EXPRESSAO>

-- SELECT * FROM FUNCIONARIO

-- INSERT INTO <TABELA> (COLUNAS) VALUES (DADOS)
-- INSERT INTO FUNCIONARIO (NOME, DATANASCIMENTO) VALUES ('MARIA DAS DORES', '1995-07-30');

-- UPDATE <TABELA> SET COLUNA = VALOR WHERE <EXPRESSÃO>
-- UPDATE FUNCIONARIO SET DATANASCIMENTO = '1996-07-30' WHERE IDF = 2;

-- DELETE FROM WHERE <EXPRESSAO>
-- DELETE FROM FUNCIONARIO WHERE IDF = 2;

-- SELECT * FROM FUNCIONARIO

-- DROP <OBJETO> -- EXCLUIR OBJETO

-- SHOW <OBJETO> -- MOSTRAR OBJETO

USE sakila;

show Tables;
show DATABASES;

DESCRIBE ACTOR;