-- mysql -u root -p

SHOW databases;
USE WORLD;
-- SQL - STRUCTURED QUERY LANGUAGE , ANSI

-- ORACLE, PL -SQL,
-- SQL-SERVER TRANSACT SQL (VISUAL BASIC)

-- DDL - DATA DEFINITION LANGUAGE

show tables;

create database AULA01;
USE AULA01;

-- CREATE TABLE <NOME_DA_TABELA> ( COLUNAS .. ) <NOME_DA_COLUNA TIPO_DE_DADO VALIDAÇÕES>
-- CHAR UF(2), CEP (8) , CPF(11) // NOME, CIDADES = VARCHAR

CREATE TABLE PESSOA( ID INT AUTO_INCREMENT,
NOME VARCHAR(50) NOT NULL,
SALARIO DECIMAL (19,2) CHECK (SALARIO > 0),
DEPARTAMENTO VARCHAR(30) DEFAULT 'OPERACIONAL',
PRIMARY KEY (ID)
);

DESC PESSOA;
DESCRIBE PESSOA;

-- INSERT INTO <TABELA> (COLUNAS) VALUES (VALORES)

INSERT INTO PESSOA (NOME, SALARIO, DEPARTAMENTO) VALUES ('JOSE DA SILVA', '5000', 'DIRETORIA');
INSERT INTO PESSOA (NOME, SALARIO) VALUES ('MARIA DA DORES', '5000');
INSERT INTO PESSOA (NOME, SALARIO) VALUES ('JOAO', '1000');

-- SELECT <COLUNAS> OU * PARA TODAS
-- FROM <TABELAS>

SELECT * FROM PESSOA;
SELECT * FROM PROJETOS;

CREATE TABLE PROJETOS (IDP INT AUTO_INCREMENT, TITULO VARCHAR (30), PRIMARY KEY (IDP));

INSERT INTO PROJETOS (TITULO) VALUES ('DESENVOLVIMENTO WEB.');
INSERT INTO PROJETOS (TITULO) VALUES ('ESPECIFICAÇÃO DE REQUISITOS');

CREATE TABLE PARTICIPACAO (IDPAR INT auto_increment, ID INT, IDP INT, PRIMARY KEY (IDPAR),
FOREIGN KEY (ID) REFERENCES PESSOA(ID),
FOREIGN KEY (IDP) REFERENCES PROJETOS (IDP) ON DELETE CASCADE);

INSERT INTO PARTICIPACAO(ID, IDP) VALUES (1,2), (2,2), (3,2);

SELECT NOME,TITULO FROM PARTICIPACAO NATURAL JOIN PESSOA NATURAL JOIN PROJETOS;

DELETE FROM PROJETOS WHERE IDP = 1;

-- ON DELETE , ON UPDATE
-- RESTRICTED - NÃO DEIXA VC EXECUTAR A OPERAÇÃO
-- NO ACTION - 
-- DEFAULT - 
-- CASCADE 

