
-- MIN () - QUE RETORNAR O MENOR VALOR DE UMA COLUNA
-- MAX () - QUE RETORNAR O MAIOR VALOR DE UMA COLUNA
-- SUM(() - QUE RETORNAR A SOMATORIA DE UMA COLUNA
-- AVG() - QUE RETORNAR A MEDIA DE UM VALOR DE UMA COLUNA
-- COUNT() - QUE CONTA A QUANTIDADE DE LINHA DE UMA TABELA


SELECT * FROM DETALHES_DO_PEDIDO;

SELECT MAX(PRECO_SUGERIDO) FROM PRODUTOS;

SHOW TABLES;

DESC PRODUTOS;

SELECT MAX(PRECO_SUGERIDO), LINHA_DO_PRODUTO
FROM PRODUTOS
GROUP BY LINHA_DO_PRODUTO;

-- O HAVING UTILIZA FAZ UMA CONSULTA DENTRO DOS DADOS AGRUPADOS OU SEJA GROUP BY
-- JA O WHERE, ELE ATUA ANTES, ELE FAZ UM FILTRO ANTES. NO CASO ELE FAZ UM FILTRO E DEPOIS O PROCESSAMENTO DO AGRUPAMENTO

SELECT MAX(PRECO_SUGERIDO), LINHA_DO_PRODUTO
FROM PRODUTOS
WHERE LINHA_DO_PRODUTO <> 'NAVIOS' AND LINHA_DO_PRODUTO <> 'AVIAO'
GROUP BY LINHA_DO_PRODUTO;

SELECT * FROM DETALHES_DO_PEDIDO;

SELECT QUANTIDADE_ENCOMENDADA * PRECO_DA_UNIDADE
FROM DETALHES_DO_PEDIDO;

-- ORDER BY SEMPRE SERÁ PROCESSADO POR ULTIMO NO CASO DO WHERE, HAVING
-- QUANDO SE UTILIZA ORDER BY, FAZ ORDENAÇÃO DE MANEIRA 'ASC' ASCENDENTE.
-- CASO QUEIRA TROVCAR 'DESC' PARA DESCENDENTE

SELECT PEDIDO_ID, SUM(QUANTIDADE_ENCOMENDADA * PRECO_DA_UNIDADE) AS TOTAL
FROM DETALHES_DO_PEDIDO
GROUP BY PEDIDO_ID
HAVING SUM(QUANTIDADE_ENCOMENDADA * PRECO_DA_UNIDADE) > 50000
ORDER BY TOTAL DESC;

SELECT * FROM DETALHES_DO_PEDIDO;
SELECT * FROM PRODUTOS;

SELECT  DP.PEDIDO_ID, P.LINHA_DO_PRODUTO, DP.PRECO_DA_UNIDADE
FROM PRODUTOS P 
INNER JOIN DETALHES_DO_PEDIDO DP
ON P.PRODUTO_ID = DP.PRODUTO_ID;


SELECT  DP.PEDIDO_ID,
SUM(DP.PRECO_DA_UNIDADE * DP.QUANTIDADE_ENCOMENDADA)
FROM PRODUTOS P 
INNER JOIN DETALHES_DO_PEDIDO DP
ON P.PRODUTO_ID = DP.PRODUTO_ID
WHERE P.LINHA_DO_PRODUTO = 'CARRO CLASSICO' 
OR P.LINHA_DO_PRODUTO = 'CARROS ANTIGOS'
GROUP BY PEDIDO_ID;


SELECT  P.LINHA_DO_PRODUTO,
SUM(DP.PRECO_DA_UNIDADE * DP.QUANTIDADE_ENCOMENDADA) AS TOTAL
FROM PRODUTOS P 
INNER JOIN DETALHES_DO_PEDIDO DP
ON P.PRODUTO_ID = DP.PRODUTO_ID
WHERE P.LINHA_DO_PRODUTO = 'CARRO CLASSICO' 
OR P.LINHA_DO_PRODUTO = 'CARROS ANTIGOS'
GROUP BY P.LINHA_DO_PRODUTO;


SELECT  P.LINHA_DO_PRODUTO,
SUM(DP.PRECO_DA_UNIDADE * DP.QUANTIDADE_ENCOMENDADA) AS TOTAL
FROM PRODUTOS P 
INNER JOIN DETALHES_DO_PEDIDO DP
ON P.PRODUTO_ID = DP.PRODUTO_ID
WHERE P.LINHA_DO_PRODUTO = 'CARRO CLASSICO' 
OR P.LINHA_DO_PRODUTO = 'CARROS ANTIGOS'
GROUP BY P.LINHA_DO_PRODUTO
HAVING TOTAL > 2000000;

SELECT  C.PRIMEIRO_NOME, SUM(P.MONTANTE_PAGO) AS TOTAL
FROM CLIENTES C
INNER JOIN PAGAMENTOS P ON P.CLIENTE_ID = C.CLIENTE_ID 
GROUP BY P.CLIENTE_ID;

SELECT  CONCAT(C.PRIMEIRO_NOME,' ',C.ULTIMO_NOME), SUM(P.MONTANTE_PAGO) AS TOTAL
FROM CLIENTES C
INNER JOIN PAGAMENTOS P ON P.CLIENTE_ID = C.CLIENTE_ID 
GROUP BY P.CLIENTE_ID;

SELECT  CONCAT(C.PRIMEIRO_NOME,' ',C.ULTIMO_NOME), SUM(P.MONTANTE_PAGO) AS TOTAL
FROM CLIENTES C
INNER JOIN PAGAMENTOS P ON P.CLIENTE_ID = C.CLIENTE_ID 
GROUP BY P.CLIENTE_ID;