
-- MIN () - QUE RETORNAR O MENOR VALOR DE UMA COLUNA
-- MAX () - QUE RETORNAR O MAIOR VALOR DE UMA COLUNA
-- SUM(() - QUE RETORNAR A SOMATORIA DE UMA COLUNA
-- AVG() - QUE RETORNAR A MEDIA DE UM VALOR DE UMA COLUNA
-- COUNT() - QUE CONTA A QUANTIDADE DE LINHA DE UMA TABELA


-- as funções de agregação são usadas juntas com a - group by

use modeloclassico;

select * from pedidos;

SELECT CLIENTE_ID, COUNT(*) FROM PEDIDOS
GROUP BY CLIENTE_ID;

SELECT * FROM DETALHES_DO_PEDIDO;

SELECT PEDIDO_ID,SUM(QUANTIDADE_ENCOMENDADA * PRECO_DA_UNIDADE) AS TOTAL
FROM DETALHES_DO_PEDIDO
GROUP BY PEDIDO_ID;

SELECT * FROM PRODUTOS;

SELECT MAX(PRECO_SUGERIDO)
FROM PRODUTOS;

SELECT MIN(PRECO_SUGERIDO)
FROM PRODUTOS;

SELECT PRODUTO_ID,AVG(QUANTIDADE_ENCOMENDADA) AS MEDIA
FROM DETALHES_DO_PEDIDO
GROUP BY PRODUTO_ID;

