
use sakila_pt;

SELECT * FROM filme;

-- 1. Quantidade total de filmes
SELECT COUNT(*) AS TOTAL_FILMES
FROM FILME;

-- 2. Duração média dos filmes
SELECT AVG(DURACAO_DO_FILME) AS DURACAO_MEDIA
FROM FILME;

-- 3. Quantidade total de filmes por categoria
SELECT * FROM CATEGORIA;
SELECT * FROM FILME_CATEGORIA;

SELECT C.NOME AS CATEGORIA, COUNT(FC.FILME_ID) AS TOTAL_FILMES
FROM CATEGORIA C
JOIN FILME_CATEGORIA FC ON C.CATEGORIA_ID = FC.CATEGORIA_ID
GROUP BY C.NOME;

-- 4. Duração média dos filmes por categoria

SELECT C.NOME AS CATEGORIA, AVG(F.DURACAO_DO_FILME) AS DURACAO_MEDIA
FROM CATEGORIA C
JOIN FILME_CATEGORIA FC ON C.CATEGORIA_ID = FC.CATEGORIA_ID
JOIN FILME F ON FC.FILME_ID = F.FILME_ID
GROUP BY C.NOME;

-- 5. Categorias com menos de 57 filmes

SELECT C.NOME AS CATEGORIA, COUNT(FC.FILME_ID) AS TOTAL_FILMES
FROM CATEGORIA C
JOIN FILME_CATEGORIA FC ON C.CATEGORIA_ID = FC.CATEGORIA_ID
GROUP BY C.NOME
HAVING COUNT(FC.FILME_ID) < 57;

-- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- 

-- 1. Maior preço sugerido

USE MODELOCLASSICO;

SELECT MAX(PRECO_SUGERIDO) AS MAIOR_PRECO_SUGERIDO
FROM PRODUTOS;

-- 2. Menor preço de custo

SELECT MIN(PRECO_DE_COMPRA) AS MENOR_PRECO_DE_COMPRA
FROM PRODUTOS;


-- 3. Preço sugerido médio por linha de produto

SELECT LINHA_DO_PRODUTO, AVG(PRECO_SUGERIDO) AS PRECO_SUGERIDO_MEDIO
FROM PRODUTOS
GROUP BY LINHA_DO_PRODUTO;

-- 4. Quantidade total em estoque por linha de produto

SELECT LINHA_DO_PRODUTO, SUM(QUANTIA_EM_ESTOQUE) AS TOTAL_EM_ESTOQUE
FROM PRODUTOS
GROUP BY LINHA_DO_PRODUTO;

