USE SAKILA_PT;


-- 1. Nome da categoria e quantidade de filmes

SELECT * FROM CATEGORIA;
SELECT * FROM FILME_CATEGORIA;

SELECT C.NOME AS CATEGORIA, COUNT(FC.FILME_ID) AS TOTAL_FILMES
FROM CATEGORIA C
JOIN FILME_CATEGORIA FC ON C.CATEGORIA_ID = FC.CATEGORIA_ID
GROUP BY C.NOME;


-- 2. Nome do cliente e total gasto em locações


SELECT CONCAT(C.PRIMEIRO_NOME, ' ', C.ULTIMO_NOME) AS CLIENTE,
SUM(P.VALOR) AS TOTAL_GASTO
FROM CLIENTE C
JOIN PAGAMENTO P ON C.CLIENTE_ID = P.CLIENTE_ID
GROUP BY C.CLIENTE_ID, C.PRIMEIRO_NOME, C.ULTIMO_NOME;


-- 3. Nome do ator e número de filmes em que atuou


SELECT CONCAT(A.PRIMEIRO_NOME, ' ', A.ULTIMO_NOME) AS ATOR,
COUNT(FA.FILME_ID) AS TOTAL_FILMES
FROM ATOR A
JOIN FILME_ATOR FA ON A.ATOR_ID = FA.ATOR_ID
GROUP BY A.ATOR_ID, A.PRIMEIRO_NOME, A.ULTIMO_NOME;


-- 4. Média de duração dos filmes por ator


SELECT CONCAT(A.PRIMEIRO_NOME, ' ', A.ULTIMO_NOME) AS ATOR,
AVG(F.DURACAO_DO_FILME) AS MEDIA_DURACAO
FROM ATOR A
JOIN FILME_ATOR FA ON A.ATOR_ID = FA.ATOR_ID
JOIN FILME F ON FA.FILME_ID = F.FILME_ID
GROUP BY A.ATOR_ID, A.PRIMEIRO_NOME, A.ULTIMO_NOME;


-- 5. Total de vendas por loja


SELECT F.LOJA_ID, SUM(P.VALOR) AS TOTAL_PAGAMENTOS
FROM PAGAMENTO P
JOIN FUNCIONARIO F ON P.FUNCIONARIO_ID = F.FUNCIONARIO_ID
GROUP BY F.LOJA_ID;


-- 6. Número de cidades por país (do mais para o menos)


SELECT PA.PAIS, COUNT(CI.CIDADE_ID) AS TOTAL_CIDADES
FROM PAIS PA
JOIN CIDADE CI ON PA.PAIS_ID = CI.PAIS_ID
GROUP BY PA.PAIS_ID, PA.PAIS
ORDER BY TOTAL_CIDADES DESC;


-- 7. Nome do cliente e valor máximo pago (apenas acima de 10.00)

SELECT CONCAT(C.PRIMEIRO_NOME, ' ', C.ULTIMO_NOME) AS CLIENTE,
MAX(P.VALOR) AS MAIOR_PAGAMENTO
FROM CLIENTE C
JOIN PAGAMENTO P ON C.CLIENTE_ID = P.CLIENTE_ID
GROUP BY C.CLIENTE_ID, C.PRIMEIRO_NOME, C.ULTIMO_NOME
HAVING MAX(P.VALOR) > 10.00;


-- 8. Nome do cliente e data do último aluguel


SELECT CONCAT(C.PRIMEIRO_NOME, ' ', C.ULTIMO_NOME) AS CLIENTE,
MAX(A.DATA_DE_ALUGUEL) AS ULTIMO_ALUGUEL
FROM CLIENTE C
JOIN ALUGUEL A ON C.CLIENTE_ID = A.CLIENTE_ID
GROUP BY C.CLIENTE_ID, C.PRIMEIRO_NOME, C.ULTIMO_NOME;


-- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- 


USE MODELOCLASSICO;

-- 1. Nome do cliente e valor total pago


SELECT CL.NOME_DO_CLIENTE, SUM(PG.MONTANTE_PAGO) AS TOTAL_PAGO
FROM CLIENTES CL
JOIN PAGAMENTOS PG ON CL.CLIENTE_ID = PG.CLIENTE_ID
GROUP BY CL.CLIENTE_ID, CL.NOME_DO_CLIENTE;


-- 2. Nome do funcionário e total de clientes atendidos


SELECT CONCAT(F.PRIMEIRO_NOME, ' ', F.ULTIMO_NOME) AS FUNCIONARIO,
COUNT(CL.CLIENTE_ID) AS TOTAL_CLIENTES
FROM FUNCIONARIOS F
JOIN CLIENTES CL ON F.FUNCIONARIO_ID = CL.FUNCIONARIO_ID
GROUP BY F.FUNCIONARIO_ID, F.PRIMEIRO_NOME, F.ULTIMO_NOME;


-- 3. Nome do produto e quantidade total vendida


SELECT P.NOME, SUM(DP.QUANTIDADE_ENCOMENDADA) AS QUANTIDADE_VENDIDA
FROM PRODUTOS P
JOIN DETALHES_DO_PEDIDO DP ON P.PRODUTO_ID = DP.PRODUTO_ID
GROUP BY P.PRODUTO_ID, P.NOME;


-- 4. Quantidade de funcionários por cidade


SELECT E.CIDADE, COUNT(F.FUNCIONARIO_ID) AS TOTAL_FUNCIONARIOS
FROM ESCRITORIOS E
JOIN FUNCIONARIOS F ON E.ESCRITORIO_ID = F.ESCRITORIO_ID
GROUP BY E.ESCRITORIO_ID, E.CIDADE;