
USE MODELOCLASSICO;

SELECT * FROM PRODUTOS;

SELECT MAX(QUANTIA_EM_ESTOQUE) FROM PRODUTOS;

-- não se pode colar o nome na mesma linha. por que dará erro - ai teria que usar group by
SELECT MAX(QUANTIA_EM_ESTOQUE), NOME 
FROM PRODUTOS;

SELECT NOME FROM PRODUTOS WHERE QUANTIA_EM_ESTOQUE> 5000;

SELECT NOME, QUANTIA_EM_ESTOQUE
FROM PRODUTOS WHERE QUANTIA_EM_ESTOQUE =
(
SELECT MAX(QUANTIA_EM_ESTOQUE) FROM PRODUTOS
);

SELECT NOME, QUANTIA_EM_ESTOQUE
FROM PRODUTOS WHERE QUANTIA_EM_ESTOQUE =
(
SELECT MIN(QUANTIA_EM_ESTOQUE) FROM PRODUTOS
);

-- OPERADORES DE CONJUNTO = IN, ANY, ALL . PODE COMBINAR COM NOT

SELECT NOME FROM PRODUTOS 
WHERE PRODUTO_ID NOT IN (
SELECT PRODUTO_ID FROM DETALHES_DO_PEDIDO);

SELECT NOME FROM PRODUTOS 
WHERE PRODUTO_ID NOT IN (
SELECT DISTINCT(PRODUTO_ID) FROM DETALHES_DO_PEDIDO);

SELECT * FROM PRODUTOS WHERE PRODUTO_ID = 'S10_1678' OR PRODUTO_ID = 'S10_1949';

-- EXISTS 

SELECT NOME FROM PRODUTOS 
WHERE PRODUTO_ID NOT IN(
SELECT DISTINCT(PRODUTO_ID) FROM DETALHES_DO_PEDIDO);

SELECT NOME FROM PRODUTOS P
WHERE NOT EXISTS (
SELECT DISTINCT(PRODUTO_ID) FROM DETALHES_DO_PEDIDO DP
WHERE P.PRODUTO_ID = DP.PRODUTO_ID);

SELECT * FROM DETALHES_DO_PEDIDO;

ALTER TABLE DETALHES_DO_PEDIDO ADD COLUMN VALOR_TOTAL DECIMAL(10,2)
GENERATED ALWAYS AS (QUANTIDADE_ENCOMENDADA * PRECO_DA_UNIDADE) VIRTUAL;

SELECT * FROM DETALHES_DO_PEDIDO; -- DEPOIS DE CRIAR UMA TABELA DE VALOR TOTAL ELE PODE RETORNAR NO INAL O VALOR TOTAL

-- ADICIONA UMA COLUNA VALOR TOTAL E ADCIONA UMA TABELA COM ESTE VALOR.

SELECT PRODUTO_ID, SUM(VALOR_TOTAL)
FROM DETALHES_DO_PEDIDO
GROUP BY PRODUTO_ID;

SELECT PRODUTO_ID, SUM(VALOR_TOTAL)
FROM DETALHES_DO_PEDIDO
GROUP BY PRODUTO_ID
ORDER BY 2 ASC;

SELECT PRODUTO_ID, SUM(VALOR_TOTAL)
FROM DETALHES_DO_PEDIDO
GROUP BY PRODUTO_ID
ORDER BY 2 DESC
LIMIT 1;

SELECT MAX(TOTAL) FROM (
SELECT PRODUTO_ID, SUM(VALOR_TOTAL) AS TOTAL
FROM DETALHES_DO_PEDIDO
GROUP BY PRODUTO_ID ) AS VENDAS_TOTAL;

-- PRODUTOS QUE FATURARAM ACIMA DA MÉDIA DE VENDAS

SELECT MAX(TOTAL) FROM (
SELECT PRODUTO_ID, AVG(VALOR_TOTAL) AS TOTAL
FROM DETALHES_DO_PEDIDO
GROUP BY PRODUTO_ID 
ORDER BY 2 DESC) AS VENDAS_TOTAL;

SELECT PRODUTO_ID, SUM(QUANTIDADE_ENCOMENDADA) FROM DETALHES_DO_PEDIDO
GROUP BY PRODUTO_ID;

SELECT AVG(TOTAL) FROM
(SELECT PRODUTO_ID, SUM(QUANTIDADE_ENCOMENDADA) AS TOTAL
FROM DETALHES_DO_PEDIDO
GROUP BY PRODUTO_ID) AS TOTAL_PRODUTO;

SELECT PRODUTO_ID, SUM(QUANTIDADE_ENCOMENDADA) AS TOTAL
FROM DETALHES_DO_PEDIDO
GROUP BY PRODUTO_ID
HAVING TOTAL > (
SELECT AVG(TOTAL) FROM
(SELECT PRODUTO_ID, SUM(QUANTIDADE_ENCOMENDADA) AS TOTAL
FROM DETALHES_DO_PEDIDO
GROUP BY PRODUTO_ID) AS TOTAL_PRODUTO);

-- CTE()

-- COM O TABLE EXPRESION UTILIZA O COMANDO WITH PARA DAR UM NOME PARA O WITH

WITH QTD_PRODUTO AS (
SELECT PRODUTO_ID, SUM(QUANTIDADE_ENCOMENDADA) AS TOTAL
FROM DETALHES_DO_PEDIDO
GROUP BY PRODUTO_ID), 
MEDIA_PRODUTO AS (
SELECT AVG(TOTAL) AS MEDIA FROM QTD_PRODUTO)
SELECT MEDIA FROM MEDIA_PRODUTO;

WITH QTD_PRODUTO AS (
SELECT PRODUTO_ID, SUM(QUANTIDADE_ENCOMENDADA) AS TOTAL
FROM DETALHES_DO_PEDIDO
GROUP BY PRODUTO_ID), 
MEDIA_PRODUTO AS (
SELECT AVG(TOTAL) AS MEDIA FROM QTD_PRODUTO)
SELECT PRODUTO_ID, TOTAL FROM QTD_PRODUTO
INNER JOIN MEDIA_PRODUTO ON QTD_PRODUTO.TOTAL > MEDIA_PRODUTO.MEDIA;