-- AULA SUBCONSULTA

USE MODELOCLASSICO;

SELECT MAX(PRECO_SUGERIDO)
FROM PRODUTOS;

SELECT PRODUTO_ID, NOME FROM PRODUTOS
WHERE PRECO_SUGERIDO = 
(
SELECT MAX(PRECO_SUGERIDO)
FROM PRODUTOS
);

SELECT * FROM PRODUTOS WHERE PRODUTO_ID = 'S10_1949';