select * from pedidos;

select PEDIDO_ID, NOME_DO_CLIENTE from pedidos NATURAL JOIN CLIENTES;

select PEDIDOS.PEDIDO_ID, CLIENTES.NOME_DO_CLIENTE
FROM PEDIDOS
INNER JOIN CLIENTES 
ON PEDIDOS.CLIENTE_ID = CLIENTES.CLIENTE_ID
