
USE modeloclassico;

SELECT * FROM CLIENTES;
SELECT * FROM PEDIDOS;

SELECT PRIMEIRO_NOME, PEDIDO_ID FROM PEDIDOS NATURAL JOIN CLIENTES;

SELECT FUNCIONARIOS.PRIMEIRO_NOME
FROM CLIENTES 
NATURAL JOIN FUNCIONARIOS;

SELECT FUNCIONARIOS.PRIMEIRO_NOME, CLIENTES.PRIMEIRO_NOME
FROM CLIENTES 
NATURAL JOIN FUNCIONARIOS;

SELECT FUNCIONARIOS.PRIMEIRO_NOME, CLIENTES.PRIMEIRO_NOME
FROM CLIENTES 
INNER JOIN FUNCIONARIOS
ON FUNCIONARIOS.FUNCIONARIO_ID = CLIENTES.FUNCIONARIO_ID;

SELECT F.PRIMEIRO_NOME, C.PRIMEIRO_NOME
FROM CLIENTES C
INNER JOIN FUNCIONARIOS F
ON F.FUNCIONARIO_ID = C.FUNCIONARIO_ID;

SELECT * FROM FUNCIONARIOS;

--

SELECT * FROM PRODUTOS;

SELECT * FROM DETALHES_DO_PEDIDO;

SELECT P.NOME, P.PRODUTO_ID
FROM PRODUTOS P
LEFT JOIN detalhes_do_pedido D
ON P.PRODUTO_ID = D.PRODUTO_ID
WHERE D.PRODUTO_ID IS NULL;

SELECT * FROM DETALHES_DO_PEDIDO WHERE PRODUTO_ID = "S18_3233";

SELECT * FROM DETALHES_DO_PEDIDO WHERE PRODUTO_ID = "S10_1678";

SELECT CIDADE FROM CLIENTES
UNION
SELECT CIDADE FROM ESCRITORIOS;

SELECT CLIENTE_ID, CIDADE FROM CLIENTES
UNION
SELECT ESCRITORIO_ID, CIDADE FROM ESCRITORIOS;

SELECT CIDADE FROM CLIENTES
UNION all
SELECT CIDADE FROM ESCRITORIOS;

SELECT CIDADE FROM CLIENTES
INTERSECT
SELECT CIDADE FROM ESCRITORIOS;

SELECT CIDADE FROM ESCRITORIOS
EXCEPT
SELECT CIDADE FROM CLIENTES;

SELECT E.CIDADE FROM ESCRITORIOS E
LEFT JOIN CLIENTES C ON C.CIDADE = E.CIDADE
WHERE C.CIDADE IS NULL

SELECT CIDADE FROM ESCRITORIOS
EXCEPT
SELECT CIDADE FROM MODELOCLASSICO.CLIENTES;

SELECT * FROM SAKILA_PT.CIDADE;

SELECT * FROM CLIENTES;

SELECT CIDADE FROM SAKILA_PT.CIDADE
UNION
SELECT CIDADE FROM MODELOCLASSICO.CLIENTES;