
CREATE TABLE FUNCIONARIO_AUDIT (
	ID INT AUTO_INCREMENT PRIMARY KEY,
	IDF INT NOT NULL,
	NOME VARCHAR(50) NOT NULL,
    CHANGEDAT DATETIME DEFAULT NULL,
    ACTION VARCHAR(50) DEFAULT NULL);

-- IRA OCORRER QUANDO UMA DESTAS ATUALIZAÇÕES OCORREREM.
-- INSERT , UPDATE, DELETE
-- ELE PODE SER DO TIPO BEFORE / AFTER
-- EXECUTANDO ANTES OU DEPOIS DA AÇÃO 

DELIMITER $$
CREATE TRIGGER BEFORE_FUNCIONARIO_UPDATE
	BEFORE UPDATE ON FUNCIONARIO
    FOR EACH ROW
BEGIN
	INSERT INTO FUNCIONARIO_AUDIT SET ACTION = 'UPDATE',
    IDF = OLD.IDF,

    NOME = OLD.NOME, CHANGEDAT = NOW();
    END$$
    DELIMITER ;