-- ================================================================================
-- GATILHOS = PROCEDIMENTO ARMAZENADO
-- EVENTOS = OPERAÇÕES DE ESCRITA (W) - INSERT , UPDATE E DELETE || (BEFORE, AFTER)
-- Validações, Fazer tarefas especificas, Auditoria.
-- ================================================================================

CREATE TABLE AUDIT_ESTOQUE (ID INT AUTO_INCREMENT, PRODUTO_ID VARCHAR(15),
QTD_OLD INT, QTD_NEW INT, DATA_UPDT DATETIME,
PRIMARY KEY(ID));

DROP TRIGGER BF_UPT_PRODUTO;

DELIMITER $$
CREATE TRIGGER BF_UPT_PRODUTO
	BEFORE UPDATE ON PRODUTOS
    FOR EACH ROW -- STATEMENT SÓ SERÁ EXECUTADO PARA ESTA SENTENÇA || ROW PARA TODAS LINHAS TODOS REGISTROS.
    BEGIN
		INSERT INTO AUDIT_ESTOQUE
        VALUES (NULL, OLD.PRODUTO_ID, OLD.QUANTIA_EM_ESTOQUE, NEW.QUANTIA_EM_ESTOQUE, NOW());
    END $$
DELIMITER ;

SELECT * FROM PRODUTOS;

-- S10_1678 7933

UPDATE PRODUTOS SET QUANTIA_EM_ESTOQUE = 7999 WHERE PRODUTO_ID = 'S10_1678';

SELECT * FROM PRODUTOS WHERE PRODUTO_ID = 'S10_1678';

SELECT * FROM AUDIT_ESTOQUE;

-- ================================================================================
-- VISÕES - VIEW | 
-- 
-- 
-- ================================================================================

-- CREATE VIEW ALGORITHM { MERGE, TMPTABLE, UNDEFINED }
-- <NOME>
-- AS
--

DROP VIEW VENDAS_POR_PRODUTO;

CREATE VIEW VENDAS_POR_PRODUTO
AS
SELECT PRODUTO_ID, SUM(QUANTIDADE_ENCOMENDADA * PRECO_DA_UNIDADE) AS TOTAL
FROM DETALHES_DO_PEDIDO
GROUP BY PRODUTO_ID
ORDER BY TOTAL DESC;

SELECT * FROM VENDAS_POR_PRODUTO;

SELECT PRODUTO_ID FROM VENDAS_POR_PRODUTO WHERE TOTAL = (
SELECT MAX(TOTAL) FROM VENDAS_POR_PRODUTO );

SELECT NOME FROM PRODUTOS WHERE PRODUTO_ID = (
SELECT PRODUTO_ID FROM VENDAS_POR_PRODUTO WHERE TOTAL = (
SELECT MAX(TOTAL) FROM VENDAS_POR_PRODUTO ) )