-- CAMADAS - 3 CAMADAS
-- NA AREA DE DADOS + REGRAS DE NEGÓCIO
-- MUITO USANDO EM CLIENTE SERVIDOR.alter
-- SEPARAÇÃO DE NEGÓCIO 
-- DESVANTAGEM -- TIPO LINGUAGEM

-- SQL ANSI. 
-- PL SQL - ORACLE
-- TRANSACT SQL - M$ SQL SERVER

-- MY SQL RODA O SQL ANSI. 

-- IN SOMENTE ENTRADA
-- OUT SAÍDA
-- IN/OUT ENTRADA E SAÍDA. 

-- PARAMETRO TIPO IN
DELIMITER $$
CREATE PROCEDURE CONSULTA_PRECO(IN ID VARCHAR (15))
BEGIN
	-- CORPO DA PROCEDURE;
	SELECT PRECO_SUGERIDO AS PRECO FROM PRODUTOS WHERE PRODUTO_ID = ID;
END $$
DELIMITER ;

DESC PRODUTOS;

SELECT * FROM PRODUTOS;

CALL CONSULTA_PRECO('S10_1678');

-- PARAMETRO TIPO OUT

DROP PROCEDURE QUANTIDADE;

DELIMITER $$
CREATE PROCEDURE QUANTIDADE(OUT QTD INT)
BEGIN
	-- CORPO DA PROCEDURE;
	SELECT sum(QUANTIA_EM_ESTOQUE) INTO QTD FROM PRODUTOS;
END $$
DELIMITER ;

SET @ESTOQUE=0;

CALL QUANTIDADE(@ESTOQUE);

SELECT @ESTOQUE;

DROP PROCEDURE METADE;

-- PROCEDURE PARA IN/OUT
DELIMITER $$
CREATE PROCEDURE METADE(INOUT VALOR INT)
BEGIN
	-- CORPO DA PROCEDURE;
	SET VALOR = VALOR/2;
END $$
DELIMITER ;

SET @VALOR = 100;
CALL METADE(@VALOR);
SELECT @VALOR;

-- ==========================

-- AS FUNCÇÕES SÃO PARECIDAS COMO PROCEDURE. MAS SÃO CHAMADAS DIFERENTE.
--
DELIMITER $$
CREATE FUNCTION LUCRO(valor DECIMAL(10.2))
RETURNS DECIMAL(10,2)
DETERMINISTIC
BEGIN
	DECLARE LUCRO DECIMAL(10,2);
	SET LUCRO = valor* 1.1;
    RETURN LUCRO;
END $$
DELIMITER ;

SELECT PRECO_DE_COMPRA, LUCRO(PRECO_DE_COMPRA) AS LUCRO FROM PRODUTOS;